# Generated by Django 6.1.1 on 2026-09-14 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarnetSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('vigente', models.BooleanField(default=True)),
                ('socio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carnet', to='biblioteca.socio')),
            ],
            options={
                'verbose_name': 'Carnet de socio',
                'verbose_name_plural': 'Carnets de socios',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion_prevista', models.DateField()),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Devuelto', 'Devuelto'), ('Atrasado', 'Atrasado'), ('Extraviado', 'Extraviado')], default='Activo', max_length=15)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='biblioteca.libro')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='biblioteca.socio')),
            ],
            options={
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.AddField(
            model_name='socio',
            name='libros',
            field=models.ManyToManyField(blank=True, related_name='socios', through='biblioteca.Prestamo', to='biblioteca.libro'),
        ),
    ]
