# Generated by Django 5.2.17 on 2026-10-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_carnetsocio_prestamo_socio_libros'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='copias',
            field=models.PositiveIntegerField(default=3, verbose_name='Copias disponibles'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='multa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
