# Generated by Django 5.2.17 on 2026-09-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascota', models.CharField(max_length=100)),
                ('dueno', models.CharField(max_length=100)),
                ('servicio', models.CharField(choices=[('Consulta', 'Consulta'), ('Vacunación', 'Vacunación'), ('Cirugía', 'Cirugía'), ('Baño', 'Baño')], max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Atendida', 'Atendida')], default='Pendiente', max_length=20)),
            ],
        ),
    ]
