# Generated by Django 5.2.17 on 2026-09-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascota', models.CharField(max_length=100, verbose_name='Mascota')),
                ('dueno', models.CharField(max_length=100, verbose_name='Dueño')),
                ('servicio', models.CharField(choices=[('Consulta', 'Consulta'), ('Vacunación', 'Vacunación'), ('Cirugía', 'Cirugía'), ('Baño', 'Baño')], max_length=20, verbose_name='Servicio')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Atendida', 'Atendida')], default='Pendiente', max_length=20, verbose_name='Estado')),
            ],
            options={
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
