# Generated by Django 6.1.1 on 2026-09-14 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('unidad', models.CharField(default='unidad', max_length=20, verbose_name='Unidad de medida')),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('colegiatura', models.CharField(max_length=20, unique=True, verbose_name='N° de colegiatura')),
                ('especialidad', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField(blank=True)),
                ('proximo_control', models.DateField(blank=True, null=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='vet.cita')),
            ],
            options={
                'verbose_name': 'Ficha clínica',
                'verbose_name_plural': 'Fichas clínicas',
            },
        ),
        migrations.CreateModel(
            name='ConsumoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='vet.cita')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='vet.insumo')),
            ],
            options={
                'verbose_name': 'Consumo de insumo',
                'verbose_name_plural': 'Consumos de insumos',
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='insumos',
            field=models.ManyToManyField(blank=True, related_name='citas', through='vet.ConsumoInsumo', to='vet.insumo'),
        ),
        migrations.AddField(
            model_name='cita',
            name='veterinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='vet.veterinario'),
        ),
    ]
